"""Verificação de ponta a ponta. Use somente com o banco de demonstração descartável."""
from pathlib import Path
from playwright.sync_api import sync_playwright

PASTA = Path('tmp/screenshots')
PASTA.mkdir(parents=True, exist_ok=True)


with sync_playwright() as p:
    browser = p.chromium.launch(channel='chrome', headless=True)
    context = browser.new_context(viewport={'width':1440,'height':1000}, locale='pt-BR', reduced_motion='reduce')
    page = context.new_page()
    erros=[]
    page.on('pageerror',lambda erro:erros.append(str(erro)))
    page.goto('http://127.0.0.1:8001')
    page.screenshot(path=str(PASTA/'login-desktop.png'), full_page=True)
    page.get_by_label('Usuário',exact=True).fill('supervisor')
    page.get_by_label('Senha',exact=True).fill('supervisor123')
    page.get_by_role('button',name='Entrar na minha conta').click()
    page.get_by_role('heading',name='Olá, Supervisor.').wait_for()
    page.screenshot(path=str(PASTA/'painel-desktop.png'),full_page=True)
    page.get_by_role('button',name='Novo registro',exact=True).click()
    page.get_by_label('Município',exact=True).fill('Fortaleza')
    page.get_by_label('Área',exact=True).fill('Centro')
    page.get_by_label('Ciclo',exact=True).fill('03')
    page.locator('#edit-form').get_by_role('button',name='Criar registro',exact=True).click()
    page.get_by_role('heading',name='Informações do dia').wait_for()
    page.get_by_role('button',name='Adicionar',exact=True).click()
    page.get_by_label('Número do quarteirão').fill('10')
    page.get_by_label('Rua / logradouro').fill('Rua das Flores')
    page.get_by_role('button',name='Salvar',exact=True).click()
    page.get_by_text('Quarteirão 10',exact=True).wait_for()
    page.get_by_role('button',name='Adicionar imóvel',exact=True).click()
    page.get_by_label('Número do imóvel').fill('150')
    page.get_by_label('Quarteirão',exact=True).select_option(label='10 · Rua das Flores')
    page.get_by_role('button',name='Salvar',exact=True).click()
    page.get_by_role('link',name='Abrir visita').click()
    page.get_by_role('heading',name='Visita ao imóvel nº 150').wait_for()
    page.get_by_role('button',name='Adicionar',exact=True).click()
    page.get_by_label('Depósitos A1',exact=True).fill('3')
    page.get_by_label('Depósitos B',exact=True).fill('2')
    page.get_by_role('button',name='Salvar',exact=True).click()
    page.get_by_role('button',name='Editar',exact=True).wait_for()
    page.screenshot(path=str(PASTA/'visita-desktop.png'),full_page=True)
    page.get_by_role('link',name='Voltar ao registro').click()
    page.get_by_role('heading',name='Informações do dia').wait_for()
    page.screenshot(path=str(PASTA/'registro-desktop.png'),full_page=True)
    page.on('dialog',lambda dialog:dialog.accept())
    page.get_by_role('button',name='Enviar registro',exact=True).click()
    page.get_by_text('Enviado',exact=True).wait_for()
    with page.expect_download() as download:
        page.get_by_role('button',name='Baixar PDF').click()
    download.value.save_as(str(PASTA/'registro.pdf'))
    page.set_viewport_size({'width':390,'height':844})
    page.get_by_role('link',name='Visão geral',exact=True).click()
    page.get_by_role('heading',name='Olá, Supervisor.').wait_for()
    page.screenshot(path=str(PASTA/'painel-celular.png'),full_page=True)
    assert page.evaluate('document.documentElement.scrollWidth <= window.innerWidth'), 'Tela com rolagem horizontal'
    page.get_by_role('link',name='Minha equipe',exact=True).click()
    page.get_by_role('heading',name='Agentes de campo').wait_for()
    page.get_by_role('button',name='Adicionar agente').click()
    page.get_by_label('Nome de usuário').fill('teste_browser_'+str(__import__('time').time_ns()))
    page.get_by_label('Senha inicial').fill('teste123')
    page.get_by_label('Nome completo').fill('Agente de teste')
    page.get_by_role('button',name='Salvar',exact=True).click()
    page.get_by_text('Agente de teste',exact=True).wait_for()
    page.get_by_role('link',name='Minha conta',exact=True).click()
    page.get_by_role('heading',name='Perfil',exact=True).wait_for()
    assert not erros, erros
    print('Fluxos do navegador OK: login, registro, quarteirão, imóvel, inspeção, envio, PDF, equipe e celular.')
    browser.close()
