from pathlib import Path
from playwright.sync_api import sync_playwright
import fitz

Path('tmp/screenshots').mkdir(parents=True,exist_ok=True)
with sync_playwright() as p:
    browser=p.chromium.launch(channel='chrome',headless=True)
    page=browser.new_page(viewport={'width':1440,'height':1100},reduced_motion='reduce')
    erros=[];page.on('pageerror',lambda erro:erros.append(str(erro)))
    page.goto('http://127.0.0.1:8001')
    page.get_by_label('Usuário',exact=True).fill('agente')
    page.get_by_label('Senha',exact=True).fill('agente123')
    page.get_by_role('button',name='Entrar na minha conta').click()
    page.get_by_role('button',name='Novo registro',exact=True).click()
    page.get_by_label('Município',exact=True).fill('Crato')
    page.get_by_label('Área',exact=True).fill('Centro')
    page.get_by_label('Ciclo',exact=True).fill('03')
    page.locator('#edit-form').get_by_role('button',name='Criar registro',exact=True).click()
    page.get_by_role('button',name='Novo boletim',exact=True).click()
    page.get_by_label('UF',exact=True).select_option('CE')
    page.get_by_label('Distrito',exact=True).fill('20ª CRES')
    page.get_by_label('Localidade',exact=True).fill('Centro')
    page.get_by_label('Subdist.',exact=True).fill('301')
    page.get_by_label('Sublocal',exact=True).fill('Setor 1')
    page.get_by_label('Quart. nº',exact=True).fill('02')
    page.locator('#edit-form').get_by_role('button',name='Criar boletim',exact=True).click()
    page.get_by_role('button',name='Adicionar imóvel',exact=True).click()
    page.get_by_label('Rua ou logradouro',exact=True).fill('Rua São João')
    page.get_by_label('Número',exact=True).fill('17')
    page.get_by_label('Lado',exact=True).fill('1')
    page.get_by_role('button',name='Salvar',exact=True).click()
    page.get_by_role('button',name='Adicionar imóvel',exact=True).click()
    page.get_by_label('Número',exact=True).fill('19')
    page.get_by_label('Tipo de imóvel',exact=True).select_option('PONTO_ESTRATEGICO')
    page.get_by_role('button',name='Salvar',exact=True).click()
    page.get_by_role('link',name='Abrir visita do imóvel 19',exact=True).wait_for()
    page.screenshot(path='tmp/screenshots/boletim-desktop.png',full_page=True)
    with page.expect_download() as download:
        page.get_by_role('button',name='Baixar PDF / imprimir',exact=True).click()
    download.value.save_as('tmp/screenshots/boletim.pdf')
    pdf=fitz.open('tmp/screenshots/boletim.pdf')
    assert len(pdf)==1
    texto=pdf[0].get_text()
    assert 'Rua São João' in texto and 'Boletim de Reconhecimento' in texto and '301' in texto
    pdf[0].get_pixmap(matrix=fitz.Matrix(1.5,1.5)).save('tmp/screenshots/boletim-pdf.png')
    page.set_viewport_size({'width':390,'height':844})
    page.screenshot(path='tmp/screenshots/boletim-celular.png',full_page=True)
    assert page.evaluate('document.documentElement.scrollWidth<=innerWidth')
    page.reload()
    page.get_by_role('link',name='Abrir visita do imóvel 19',exact=True).click()
    page.get_by_role('heading',name='Visita ao imóvel nº 19',exact=True).wait_for()
    assert not erros,erros
    print('Boletim OK: cabeçalho, imóveis, ponto estratégico, persistência, PDF, visita e celular.')
    browser.close()
