"""estrutura_inicial

Revisão: 0bc1e56c298d
Anterior: 
"""
from alembic import op
import sqlalchemy as sa


revision = '0bc1e56c298d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessoes_revogadas',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('expira_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('AGENTE', 'SUPERVISOR', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('municipio', sa.String(length=100), nullable=True),
    sa.Column('supervisor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('registros_diarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=True),
    sa.Column('agente_id', sa.Integer(), nullable=False),
    sa.Column('municipio', sa.String(length=100), nullable=False),
    sa.Column('codigo_area', sa.String(length=50), nullable=False),
    sa.Column('ciclo', sa.String(length=50), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('zona', sa.String(length=50), nullable=True),
    sa.Column('atividade', sa.Enum('LI', 'LI_T', 'PE', 'PE_T', 'DF', 'PVE', 'OUTROS', name='tipoatividade'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_SYNC', 'SYNCED', name='statusregistro'), nullable=False),
    sa.Column('concluido', sa.Boolean(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('resumo_imoveis_trabalhados', sa.Integer(), nullable=True),
    sa.Column('resumo_pendencias', sa.Integer(), nullable=True),
    sa.Column('resumo_depositos_inspecionados', sa.Integer(), nullable=True),
    sa.Column('resumo_imoveis_com_especimes', sa.Integer(), nullable=True),
    sa.Column('resumo_totais_tratamento', sa.Integer(), nullable=True),
    sa.Column('resumo_exemplares', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agente_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registros_diarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registros_diarios_agente_id'), ['agente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registros_diarios_client_id'), ['client_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_registros_diarios_id'), ['id'], unique=False)

    op.create_table('quarteiroes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=True),
    sa.Column('registro_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('sequencia', sa.Integer(), nullable=True),
    sa.Column('lado', sa.String(length=20), nullable=True),
    sa.Column('logradouro', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['registro_id'], ['registros_diarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quarteiroes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quarteiroes_client_id'), ['client_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_quarteiroes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quarteiroes_registro_id'), ['registro_id'], unique=False)

    op.create_table('imoveis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=True),
    sa.Column('registro_id', sa.Integer(), nullable=False),
    sa.Column('quarteirao_id', sa.Integer(), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('tipo', sa.Enum('RESIDENCIAL', 'COMERCIAL', 'TERRENO', 'OUTRO', name='tipoimovel'), nullable=True),
    sa.Column('hora_entrada', sa.String(length=10), nullable=True),
    sa.Column('tipo_visita', sa.Enum('NORMAL', 'RECUSA', 'FECHADO', 'RECUPERADO', name='tipovisita'), nullable=True),
    sa.Column('pendencia', sa.Enum('NENHUMA', 'FECHADO', 'RECUSA', 'OUTRA', name='pendencia'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quarteirao_id'], ['quarteiroes.id'], ),
    sa.ForeignKeyConstraint(['registro_id'], ['registros_diarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('imoveis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_imoveis_client_id'), ['client_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_imoveis_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_imoveis_registro_id'), ['registro_id'], unique=False)

    op.create_table('coletas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=True),
    sa.Column('imovel_id', sa.Integer(), nullable=False),
    sa.Column('numero_amostra', sa.String(length=50), nullable=False),
    sa.Column('tubito_inicial', sa.Integer(), nullable=False),
    sa.Column('tubito_final', sa.Integer(), nullable=False),
    sa.Column('quantidade_tubitos', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['imovel_id'], ['imoveis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coletas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coletas_client_id'), ['client_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_coletas_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coletas_imovel_id'), ['imovel_id'], unique=False)

    op.create_table('depositos_eliminados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=True),
    sa.Column('imovel_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['imovel_id'], ['imoveis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('depositos_eliminados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_depositos_eliminados_client_id'), ['client_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_depositos_eliminados_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_depositos_eliminados_imovel_id'), ['imovel_id'], unique=False)

    op.create_table('especimes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=True),
    sa.Column('imovel_id', sa.Integer(), nullable=False),
    sa.Column('especie', sa.String(length=100), nullable=False),
    sa.Column('larvas', sa.Integer(), nullable=True),
    sa.Column('pupas', sa.Integer(), nullable=True),
    sa.Column('pupa_aedes', sa.Integer(), nullable=True),
    sa.Column('adultos', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['imovel_id'], ['imoveis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('especimes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_especimes_client_id'), ['client_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_especimes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_especimes_imovel_id'), ['imovel_id'], unique=False)

    op.create_table('fotos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=True),
    sa.Column('imovel_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filepath', sa.String(length=500), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['imovel_id'], ['imoveis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fotos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fotos_client_id'), ['client_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_fotos_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fotos_imovel_id'), ['imovel_id'], unique=False)

    op.create_table('inspecoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=True),
    sa.Column('imovel_id', sa.Integer(), nullable=False),
    sa.Column('a1', sa.Integer(), nullable=True),
    sa.Column('a2', sa.Integer(), nullable=True),
    sa.Column('b', sa.Integer(), nullable=True),
    sa.Column('c', sa.Integer(), nullable=True),
    sa.Column('d1', sa.Integer(), nullable=True),
    sa.Column('d2', sa.Integer(), nullable=True),
    sa.Column('e', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['imovel_id'], ['imoveis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inspecoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspecoes_client_id'), ['client_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_inspecoes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspecoes_imovel_id'), ['imovel_id'], unique=False)

    op.create_table('tratamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=True),
    sa.Column('imovel_id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.Enum('LARVICIDA_1', 'LARVICIDA_2', 'ADULTICIDA', name='categoriatratamento'), nullable=False),
    sa.Column('produto', sa.String(length=100), nullable=True),
    sa.Column('quantidade', sa.Float(), nullable=True),
    sa.Column('depositos_tratados', sa.Integer(), nullable=True),
    sa.Column('cargas', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['imovel_id'], ['imoveis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tratamentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tratamentos_client_id'), ['client_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_tratamentos_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tratamentos_imovel_id'), ['imovel_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tratamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tratamentos_imovel_id'))
        batch_op.drop_index(batch_op.f('ix_tratamentos_id'))
        batch_op.drop_index(batch_op.f('ix_tratamentos_client_id'))

    op.drop_table('tratamentos')
    with op.batch_alter_table('inspecoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspecoes_imovel_id'))
        batch_op.drop_index(batch_op.f('ix_inspecoes_id'))
        batch_op.drop_index(batch_op.f('ix_inspecoes_client_id'))

    op.drop_table('inspecoes')
    with op.batch_alter_table('fotos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fotos_imovel_id'))
        batch_op.drop_index(batch_op.f('ix_fotos_id'))
        batch_op.drop_index(batch_op.f('ix_fotos_client_id'))

    op.drop_table('fotos')
    with op.batch_alter_table('especimes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_especimes_imovel_id'))
        batch_op.drop_index(batch_op.f('ix_especimes_id'))
        batch_op.drop_index(batch_op.f('ix_especimes_client_id'))

    op.drop_table('especimes')
    with op.batch_alter_table('depositos_eliminados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_depositos_eliminados_imovel_id'))
        batch_op.drop_index(batch_op.f('ix_depositos_eliminados_id'))
        batch_op.drop_index(batch_op.f('ix_depositos_eliminados_client_id'))

    op.drop_table('depositos_eliminados')
    with op.batch_alter_table('coletas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coletas_imovel_id'))
        batch_op.drop_index(batch_op.f('ix_coletas_id'))
        batch_op.drop_index(batch_op.f('ix_coletas_client_id'))

    op.drop_table('coletas')
    with op.batch_alter_table('imoveis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_imoveis_registro_id'))
        batch_op.drop_index(batch_op.f('ix_imoveis_id'))
        batch_op.drop_index(batch_op.f('ix_imoveis_client_id'))

    op.drop_table('imoveis')
    with op.batch_alter_table('quarteiroes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quarteiroes_registro_id'))
        batch_op.drop_index(batch_op.f('ix_quarteiroes_id'))
        batch_op.drop_index(batch_op.f('ix_quarteiroes_client_id'))

    op.drop_table('quarteiroes')
    with op.batch_alter_table('registros_diarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registros_diarios_id'))
        batch_op.drop_index(batch_op.f('ix_registros_diarios_client_id'))
        batch_op.drop_index(batch_op.f('ix_registros_diarios_agente_id'))

    op.drop_table('registros_diarios')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('sessoes_revogadas')
    # ### end Alembic commands ###
